src/HC.Assessment.Web/Controllers/BagsController.cs
using HC.Assessment.Domain.Entities;
using HC.Assessment.Infra.Data.ORM.EF;
using HC.Assessment.Web.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HC.Assessment.Web.Controllers
{
    public class BagsController : Controller
    {
        private AssessmentDbContext db = new AssessmentDbContext();

        // GET: Bags
        public ActionResult Index()
        {
            List<BagView> bagview = new List<BagView>();
            
            foreach (var bv in db.Bags.ToList())
			{
				switch (bv.Type)
				{
                    case "SHIRT":
                        var shirt = db.Shirts.Where(s => s.Id.Equals(bv.IdProduct)).FirstOrDefault();
                        bagview.Add(new BagView() { Id = bv.Id, IdProduct = bv.IdProduct, Description = shirt.Description, FilePath = shirt.FilePath, Price = shirt.Price });                     
                        break;
                    case "TIE":
                        var tie = db.Ties.Where(t => t.Id.Equals(bv.IdProduct)).FirstOrDefault();
                        bagview.Add(new BagView() { Id = bv.Id, IdProduct = bv.IdProduct, Description = tie.Description, FilePath = tie.FilePath, Price = tie.Price });
                        break;
                    case "CUFFLINK":
                        var cufflink = db.Cufflinks.Where(c => c.Id.Equals(bv.IdProduct)).FirstOrDefault();
                        bagview.Add(new BagView() { Id = bv.Id, IdProduct = bv.IdProduct, Description = cufflink.Description, FilePath = cufflink.FilePath, Price = cufflink.Price });
                        break;
				}				
			}
            return View("Index", "_Layout", bagview);
        }
        
        [HttpPost]
        public ActionResult SaveBag(int id, string type)
		{
            if (ModelState.IsValid)
            {
                db.Bags.Add(new Bags
                {
                    IdProduct = id,
                    Type = type
                });
                db.SaveChanges();

                return Json(new { success = true, message = "Product has added in the bag!" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                //IEnumerable<ModelError> errors = ModelState.Values.SelectMany(items => items.Errors).;

                //var errors = ModelState.Values.SelectMany(m => m.Errors).Select(e => e.ErrorMessage).ToList();

                var errors = string.Join("<br>", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));   // html break instead of " | "

                return Json(new { success = false, message = errors }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Cancel()
        {
            return RedirectToAction("Index");
        }

		// GET: Shirts/Delete/5
		public async Task<ActionResult> Delete(int? id)
		{
			BagView bagview = new BagView();

			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Bags bags = await db.Bags.FindAsync(id);

			switch (bags.Type)
			{
				case "SHIRT":
					var shirt = db.Shirts.Where(s => s.Id.Equals(bags.IdProduct)).FirstOrDefault();
					bagview.Id = bags.Id;
                    bagview.Description = shirt.Description;
                    bagview.Price = shirt.Price;
                    bagview.FilePath = shirt.FilePath;
					break;
				case "TIE":
					var tie = db.Ties.Where(t => t.Id.Equals(bags.IdProduct)).FirstOrDefault();
                    bagview.Id = bags.Id;
                    bagview.Description = tie.Description;
                    bagview.Price = tie.Price;
                    bagview.FilePath = tie.FilePath;
                    break;
				case "CUFFLINK":
					var cufflink = db.Cufflinks.Where(c => c.Id.Equals(bags.IdProduct)).FirstOrDefault();
                    bagview.Id = bags.Id;
                    bagview.Description = cufflink.Description;
                    bagview.Price = cufflink.Price;
                    bagview.FilePath = cufflink.FilePath;
                    break;
			}

			if (bagview == null)
			{
				return HttpNotFound();
			}
			return PartialView(bagview);
		}

		// POST: Shirts/Delete/5
		[HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Bags bags = await db.Bags.FindAsync(id);
            db.Bags.Remove(bags);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/HC.Assessment.Web/Views/Bags/Delete.cshtml
@model HC.Assessment.Web.Entity.BagView

@{
	ViewBag.Title = "Delete";
}

<div class="modal-dialog">
	<div class="modal-content">
		<br />
		<div class="x_panel">
			<div class="alert alert-error" role="alert">
				<h2>Bag</h2>
				<div class="clearfix"></div>
			</div>

			<div class="modal-body">
				<div class="form-horizontal">
					<div class="row">
						<div class="x_panel">
							<div class="x_title">
								<h2>@ViewBag.Title</h2>
								<ul class="nav navbar-right panel_toolbox">
									<li>
										<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
									</li>
									<li>
										<a class="close-link"><i class="fa fa-close"></i></a>
									</li>
								</ul>
								<div class="clearfix"></div>
							</div>
							<div class="x_content">
								<br />
								<h2 style="text-align:center">Are you sure you want to delete this?</h2>
								<br />
								<dl class="dl-horizontal">
									<dt>
										@Html.DisplayNameFor(model => model.Description)
									</dt>

									<dd>
										@Html.DisplayFor(model => model.Description)
									</dd>

									<dt>
										@Html.DisplayNameFor(model => model.Price)
									</dt>

									<dd>
										@Html.DisplayFor(model => model.Price)
									</dd>

									<dt>

									</dt>

									<dd>
										@if (Model.FilePath != null)
										{
											<img src="@(Model.FilePath)" alt="Image" height="100" width="100" />
										}
									</dd>
								</dl>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="modal-footer">
				@using (Html.BeginForm("Delete", "Bags", FormMethod.Post, new { id = "formBags" }))
				{
					@Html.AntiForgeryToken()
					@Html.HiddenFor(model => model.Id)
					<div class="form-actions no-color">
						<input type="button" value="Cancel" class="btn btn-primary" onclick="location.href='@Url.Action("Cancel", "Bags")'" data-dismiss="modal" />
						<input id="submitAction" type="submit" value="Delete" class="btn btn-success" />
					</div>
				}
			</div>
		</div>
	</div>
</div>

@Scripts.Render("~/bundles/jqueryval")

src/HC.Assessment.Web/Views/Bags/Index.cshtml
@model IEnumerable<HC.Assessment.Web.Entity.BagView>

<div class="modal fade" id="bagsModal" role="dialog">
	@*<div class="modal-dialog modal-lg">
			<div id="mainContent" class="modal-content col-lg-12">
			</div>
		</div>*@
</div>

<div class="col-md-12 col-sm-12 ">
	<div class="x_panel">
		<div class="x_title">
			<h2>Bag</h2>
			<ul class="nav navbar-right panel_toolbox">
				<li>
					<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				</li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">
			<div class="row">
				<div class="col-sm-12">
					<div class="card-box table-responsive">
						<table id="datatable" class="table table-striped table-bordered table-hover" style="width:100%">
							<thead>
								<tr>
									<th>Id</th>
									@*<th>Product Id</th>*@
									<th>Description</th>
									<th>Price</th>
									<th>Image</th>
									<th class="text-right">Action</th>
								</tr>
							</thead>


							<tbody>
								@foreach (var item in Model)
								{
								<tr>
									<td>
										@Html.DisplayFor(modelItem => item.Id)
									</td>
									@*<td>
										@Html.DisplayFor(modelItem => item.IdProduct)
									</td>*@
									<td>
										@Html.DisplayFor(modelItem => item.Description)
									</td>
									<td>
										@Html.DisplayFor(modelItem => item.Price)
									</td>
									<td>
										@if (item.FilePath != null)
										{
											<img src="@Url.Content(item.FilePath)" alt="Image" height="100" width="100" />
										}
									</td>
									<td align="right">
										<a href="javascript:void(0);" class="glyphicon glyphicon-trash red deleteAction" data-id="@item.Id" title="Delete"></a>&nbsp;
									</td>
								</tr>
								}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@section scripts{
	<script type="text/javascript">
		var DeletePostBackURL = '/Bags/Delete?id=';

		$(function () {
			$(".deleteAction").click(function () {
				debugger;
				var id = $(this).attr("data-id");
				$("#bagsModal").load(DeletePostBackURL + id, function () {
					$("#bagsModal").modal('show');
				});
			});
		});
	</script>
}