src/HC.Assessment.Web/Controllers/TiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HC.Assessment.Infra.Data.ORM.EF;
using HC.Assessment.Domain.Entities;
using System.IO;

namespace HC.Assessment.Web.Controllers
{
    public class TiesController : Controller
    {
        private AssessmentDbContext db = new AssessmentDbContext();

        // GET: Ties
        public async Task<ActionResult> Index()
        {
            return View("Index", "_Layout", await db.Ties.ToListAsync());
            //return View(await db.Ties.ToListAsync());
        }

        // GET: Ties/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ties ties = await db.Ties.FindAsync(id);
            if (ties == null)
            {
                return HttpNotFound();
            }
            return PartialView(ties);
        }
        public ActionResult Cancel()
        {
            return RedirectToAction("Index");
        }

        // GET: Ties/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Ties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create([Bind(Include = "Id,Description,Details,Price,FilePath")] Ties ties)
        public ActionResult Create(Ties ties, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Images/Ties"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                db.Ties.Add(new Ties
                {
                    Description = ties.Description,
                    Details = ties.Details,
                    Price = ties.Price,
                    FilePath = "Images/Ties/" + file.FileName
                });
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ties);
        }

        // GET: Ties/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ties ties = await db.Ties.FindAsync(id);
            if (ties == null)
            {
                return HttpNotFound();
            }
            return PartialView(ties);
        }

        // POST: Ties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Ties ties, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string path = Path.Combine(Server.MapPath("~/Images/Ties"), Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    ties.FilePath = "Images/Ties/" + file.FileName;
                }
                db.Entry(ties).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ties);
        }

        // GET: Ties/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ties ties = await db.Ties.FindAsync(id);
            if (ties == null)
            {
                return HttpNotFound();
            }
            return PartialView(ties);
        }

        // POST: Ties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Ties ties = await db.Ties.FindAsync(id);
            db.Ties.Remove(ties);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/HC.Assessment.Web/Views/Ties/Create.cshtml
@model HC.Assessment.Domain.Entities.Ties

@{
	ViewBag.Title = "Create";
}

@{ Layout = null;}

<div class="modal-dialog modal-lg">
	<div class="modal-content col-lg-12">
		<br />
		@using (Html.BeginForm("Create", "Ties", FormMethod.Post, new { enctype = "multipart/form-data" }))
		{
			@Html.AntiForgeryToken()
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			<div class="x_panel">
				<div class="alert alert-success" role="alert">
					<h2>Ties</h2>
					<div class="clearfix"></div>
				</div>

				<div class="modal-body">
					<div class="form-horizontal">
						<div class="row">
							<div class="x_panel">
								<div class="x_title">
									<h2>@ViewBag.Title</h2>
									<ul class="nav navbar-right panel_toolbox">
										<li>
											<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
										</li>
										<li>
											<a class="close-link"><i class="fa fa-close"></i></a>
										</li>
									</ul>
									<div class="clearfix"></div>
								</div>
								<div class="x_content">
									<br />

									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="description">
											Description <span class="required">*</span>
										</label>
										<div class="col-md-6 col-sm-6 ">
											@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @maxlength = "80", @data_val = "true", @required = "required" } })
											@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="details">
											Details <span class="required">*</span>
										</label>
										<div class="col-md-6 col-sm-6 ">
											@Html.TextAreaFor(model => model.Details, new { @maxlength = 2000, @class = "form-control" })
										</div>
									</div>
									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="description">
											Price <span class="required">*</span>
										</label>
										<div class="col-md-3 col-sm-3 ">
											@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @maxlength = "10", @data_val = "true", @required = "required" } })
											@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="image">
											Image
										</label>
										<div class="col-md-10">
											<input type="file" name="file" />

										</div>
									</div>
									<div class="ln_solid"></div>

									<div class="item form-group">
										<div class="col-md-6 col-sm-6 offset-md-3">
											<input type="button" value="Cancel" class="btn btn-primary" onclick="location.href='@Url.Action("Cancel", "Ties")'" data-dismiss="modal" />
											<input id="submitAction" type="submit" value="Submit" class="btn btn-success" />; @*onclick="location.href='@Url.Action("Index", "Ties")'"/>*@
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>

@Scripts.Render("~/bundles/jqueryval")

src/HC.Assessment.Web/Views/Ties/Delete.cshtml
@model HC.Assessment.Domain.Entities.Ties

@{
	ViewBag.Title = "Delete";
}

<div class="modal-dialog">
	<div class="modal-content">
		<br />
		<div class="x_panel">
			<div class="alert alert-error" role="alert">
				<h2>Ties</h2>
				<div class="clearfix"></div>
			</div>

			<div class="modal-body">
				<div class="form-horizontal">
					<div class="row">
						<div class="x_panel">
							<div class="x_title">
								<h2>@ViewBag.Title</h2>
								<ul class="nav navbar-right panel_toolbox">
									<li>
										<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
									</li>
									<li>
										<a class="close-link"><i class="fa fa-close"></i></a>
									</li>
								</ul>
								<div class="clearfix"></div>
							</div>
							<div class="x_content">
								<br />
								<h2 style="text-align:center">Are you sure you want to delete this?</h2>
								<br />
								<dl class="dl-horizontal">
									<dt>
										@Html.DisplayNameFor(model => model.Description)
									</dt>

									<dd>
										@Html.DisplayFor(model => model.Description)
									</dd>

									<dt>
										@Html.DisplayNameFor(model => model.Details)
									</dt>

									<dd>
										@Html.DisplayFor(model => model.Details)
									</dd>

									<dt>
										@Html.DisplayNameFor(model => model.Price)
									</dt>

									<dd>
										@Html.DisplayFor(model => model.Price)
									</dd>

									<dt>

									</dt>

									<dd>
										@if (Model.FilePath != null)
										{
											<img src="@(Model.FilePath)" alt="Image" height="100" width="100" />
										}
									</dd>
								</dl>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="modal-footer">
				@using (Html.BeginForm("Delete", "Ties", FormMethod.Post, new { id = "formShirts" }))
				{
					@Html.AntiForgeryToken()
					@Html.HiddenFor(model => model.Id)
					<div class="form-actions no-color">
						<input type="button" value="Cancel" class="btn btn-primary" onclick="location.href='@Url.Action("Cancel", "Ties")'" data-dismiss="modal" />
						<input id="submitAction" type="submit" value="Delete" class="btn btn-success" />
					</div>
				}
			</div>
		</div>
	</div>
</div>

@Scripts.Render("~/bundles/jqueryval")

src/HC.Assessment.Web/Views/Ties/Details.cshtml
@model HC.Assessment.Domain.Entities.Ties

@{
	ViewBag.Title = "Details";
}

<div class="modal-dialog modal-lg">
	<div class="modal-content col-lg-12">
		<br />
		<div class="x_panel">
			<div class="alert alert-success" role="alert">
				<h2>Country</h2>
				<div class="clearfix"></div>
			</div>

			<div class="modal-body">
				<div class="form-horizontal">
					<div class="row">
						<div class="x_panel">
							<div class="x_title">
								<h2>@ViewBag.Title</h2>
								<ul class="nav navbar-right panel_toolbox">
									<li>
										<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
									</li>
									<li>
										<a class="close-link"><i class="fa fa-close"></i></a>
									</li>
								</ul>
								<div class="clearfix"></div>
							</div>
							<div class="x_content">
								<br />
								<dl class="dl-horizontal">
									<dt>
										@Html.DisplayNameFor(model => model.Description)
									</dt>

									<dd>
										@Html.DisplayFor(model => model.Description)
									</dd>

									<dt>
										@Html.DisplayNameFor(model => model.Details)
									</dt>

									<dd>
										@Html.DisplayFor(model => model.Details)
									</dd>

									<dt>
										@Html.DisplayNameFor(model => model.Price)
									</dt>

									<dd>
										@Html.DisplayFor(model => model.Price)
									</dd>

									<dt>

									</dt>

									<dd>
										@if (Model.FilePath != null)
										{
											<img src="@(Model.FilePath)" alt="Image" height="100" width="100" />
										}
									</dd>
								</dl>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="modal-footer">
				@*<input type="button" value="Cancelar" class="btn btn-warning btn-transparent" data-dismiss="modal" />*@
				<input type="button" value="Cancel" class="btn btn-primary" onclick="location.href='@Url.Action("Cancel", "Ties")'" data-dismiss="modal" />
			</div>

		</div>
	</div>
</div>

src/HC.Assessment.Web/Views/Ties/Edit.cshtml
@model HC.Assessment.Domain.Entities.Ties

@{
	ViewBag.Title = "Edit";
}

@{ Layout = null;}

<div class="modal-dialog modal-lg">
	<div class="modal-content col-lg-12">
		<br />
		@using (Html.BeginForm("Edit", "Ties", FormMethod.Post, new { enctype = "multipart/form-data" }))
		{
			@Html.AntiForgeryToken()
			@Html.HiddenFor(model => model.Id)
			@Html.HiddenFor(model => model.FilePath)
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			<div class="x_panel">
				<div class="alert alert-success" role="alert">
					<h2>Ties</h2>
					<div class="clearfix"></div>
				</div>

				<div class="modal-body">
					<div class="form-horizontal">
						<div class="row">
							<div class="x_panel">
								<div class="x_title">
									<h2>@ViewBag.Title</h2>
									<ul class="nav navbar-right panel_toolbox">
										<li>
											<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
										</li>
										<li>
											<a class="close-link"><i class="fa fa-close"></i></a>
										</li>
									</ul>
									<div class="clearfix"></div>
								</div>
								<div class="x_content">
									<br />

									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="description">
											Description <span class="required">*</span>
										</label>
										<div class="col-md-6 col-sm-6 ">
											@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @maxlength = "80", @data_val = "true", @required = "required" } })
											@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="details">
											Details <span class="required">*</span>
										</label>
										<div class="col-md-6 col-sm-6 ">
											@Html.TextAreaFor(model => model.Details, new { @maxlength = 2000, @class = "form-control" })
										</div>
									</div>
									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="price">
											Price <span class="required">*</span>
										</label>
										<div class="col-md-3 col-sm-3 ">
											@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @maxlength = "10", @data_val = "true", @required = "required" } })
											@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
										</div>
									</div>
									<div class="item form-group">
										<label class="col-form-label col-md-3 col-sm-3 label-align" for="image">
											Image
										</label>
										<div class="col-md-10">
											<input type="file" name="file" />

										</div>
									</div>
									<div class="ln_solid"></div>

									<div class="item form-group">
										<div class="col-md-6 col-sm-6 offset-md-3">
											<input type="button" value="Cancel" class="btn btn-primary" onclick="location.href='@Url.Action("Cancel", "Ties")'" data-dismiss="modal" />
											<input id="submitAction" type="submit" value="Submit" class="btn btn-success" />; @*onclick="location.href='@Url.Action("Index", "Ties")'"/>*@
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>

@Scripts.Render("~/bundles/jqueryval")

src/HC.Assessment.Web/Views/Ties/Index.cshtml
@model IEnumerable<HC.Assessment.Domain.Entities.Ties>

<p>
	<a href="javascript:void(0);" class="btn btn-success createAction">
		<span class="glyphicon glyphicon-plus"></span>
		Create New
	</a>

</p>

<div class="modal fade" id="tiesModal" role="dialog">
	@*<div class="modal-dialog modal-lg">
			<div id="mainContent" class="modal-content col-lg-12">
			</div>
		</div>*@
</div>

<div class="col-md-12 col-sm-12 ">
	<div class="x_panel">
		<div class="x_title">
			<h2>Ties</h2>
			<ul class="nav navbar-right panel_toolbox">
				<li>
					<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
				</li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">
			<div class="row">
				<div class="col-sm-12">
					<div class="card-box table-responsive">
						<table id="datatable" class="table table-striped table-bordered table-hover" style="width:100%">
							<thead>
								<tr>
									<th>Description</th>
									<th>Details</th>
									<th>Price</th>
									<th>Image</th>
									<th class="text-right">Action</th>
								</tr>
							</thead>


							<tbody>
								@foreach (var item in Model)
								{
									<tr>
										<td>
											@Html.DisplayFor(modelItem => item.Description)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Details)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Price)
										</td>
										<td>
											@if (item.FilePath != null)
											{
												<img src="@Url.Content(item.FilePath)" alt="Image" height="100" width="100" />
											}
										</td>
										<td align="right">
											<a href="javascript:void(0);" class="glyphicon glyphicon-list green detailAction" data-id="@item.Id" title="Details"></a>&nbsp;
											<a href="javascript:void(0);" class="glyphicon glyphicon-edit blue editAction" data-id="@item.Id" title="Edit"></a>&nbsp;
											<a href="javascript:void(0);" class="glyphicon glyphicon-trash red deleteAction" data-id="@item.Id" title="Delete"></a>&nbsp;
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@section scripts{
	<script type="text/javascript">
		var DetailPostBackURL = '/Ties/Details?id=';
		var EditPostBackURL = '/Ties/Edit?id=';
		var CreatePostBackURL = '/Ties/Create';
		var DeletePostBackURL = '/Ties/Delete?id=';

		$(function () {
			$(".detailAction").click(function () {
				debugger;
				var id = $(this).attr("data-id");
				$("#tiesModal").load(DetailPostBackURL + id, function () {
					$("#tiesModal").modal('show');
				});
			});

			$(".editAction").click(function () {
				var id = $(this).attr("data-id");
				$("#tiesModal").load(EditPostBackURL + id, function () {
					$("#tiesModal").modal('show');
				});
			});

			$(".createAction").click(function () {
				$("#tiesModal").load(CreatePostBackURL, function () {
					$("#tiesModal").modal('show');
				});
			});

			$(".deleteAction").click(function () {
				debugger;
				var id = $(this).attr("data-id");
				$("#tiesModal").load(DeletePostBackURL + id, function () {
					$("#tiesModal").modal('show');
				});
			});
		});
	</script>
}